services:
  backend:
    container_name: msp_backend
    build: .
    ports:
      - 3000:3000
      - 9229:9229 # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:docker
    depends_on:
      - postgres
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres@postgres/msp_dev

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432 # enables connecting locally via psql
    environment:
      POSTGRES_DB: msp_dev
      POSTGRES_HOST_AUTH_METHOD: trust
