services:
  backend:
    container_name: msp_backend
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229 # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:docker
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}@postgres/${POSTGRES_DB}

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT} # enables connecting locally via psql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
